### ISSUE TITLE
Why isn't this open source?

### ISSUE THREAD

**Issue by KaueTheTrekker** [LibreScore/app-librescore#23]
Is this actually open source, where's the source code for the app?

**Comment by IzzySoft** [comment]
You ap is curently [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/org.librescore.librescore).But while this Git repo says it's MIT licensed, I indeed find no code here –and the code in [LibreScore](https://github.com/LibreScore/LibreScore) has not been updated for 2 years while there are steady releases being published. Without the source code being available, I'd have to remove the app again from my repo. So can you please point out and make it available?

**Comment by sealsrock12** [comment]
The app is not open-source. The MIT license does not give any rights for source code. It is just for "a copy of this software and associated documentation files."

https://github.com/LibreScore/LibreScore is a different program.

**Comment by IzzySoft** [comment]
Thanks for the clear words – removing it from my repo then.

**Comment by PeterNjeim** [comment]
> Is this actually open source, where's the source code for the app?

LibreScore is the name of a suite of programs, all of which were open source, until the release of this app. The app unfortunately retains the "Libre" name as that is what Xmader named the whole suite. This app will remain the only closed-source program in the LibreScore suite until an unspecified future date.

**Comment by grh0** [comment]
Is there a particular reason why the App is closed?
It's pretty confusing TBH.
One usually associates software with "libre" in the title as Gnu licensed project ... but at least open source.
This particular aspect appears to be neither.

I sincerely hope the intention is not to mislead...

**Comment by PeterNjeim** [comment]
The MIT license is also considered "libre". I will reiterate once again, the name of the suite, which was decided years ago by Xmader, is "LibreScore", and all the software he made was open source, as expected. Then one day we decided to make an app, this is well after Xmader already left the project. The name of the app is "LibreScore" because that's the name of the suite, it's unfortunate but at this point "LibreScore' is a brand name. The reason it's closed source is explained in the Discord server. Keep bug reports in GitHub, and meta discussion in Discord, thanks.
