### ISSUE TITLE
Android/Windows: cannot find official tabs

### ISSUE THREAD

**Issue by srghma** [LibreScore/app-librescore#5]
cannot find Radiohead Creep official tab in Windows app (and Android)

![VirtualBox_win10_19_12_2021_20_48_18](https://user-images.githubusercontent.com/7573215/146687074-ff246a53-89a4-49e9-9591-27c8fee7431d.png)

but can in browser

![2021-12-19-08pm-48-52-screenshot](https://user-images.githubusercontent.com/7573215/146687088-8be24794-3528-4b39-ab19-817d388825c8.png)

**Comment by SealsRock12** [comment]
Official scores aren't supported at this time.

**Comment by srghma** [comment]
ok, tnx

---

just for the info I dont have pro+ subscription (I did have)
but I'm still able to download pdf, midi, mp3

but "Individual parts" and mscz fails with ipfs error

![2021-12-19-09pm-03-21-screenshot](https://user-images.githubusercontent.com/7573215/146687483-cff27a43-25ca-404d-806e-06af3af247e1.png)

---------

additional question:
Do You think it's in principle possible to implement download of 
1) mscz
2) individual midi parts (that's what I actually would like to have)
without having subscription?

**Comment by SealsRock12** [comment]
First off, you are using an outdated version of the script. We have a new repo at https://github.com/LibreScore/dl-musescore. Maybe MuseScore lets you retain access to the scores even after you lose your pro+ subscription, or you still have it and are paying for it without your knowledge.

1. Not yet, for reasons we cannot explain yet
2. No, because the website requires user-specific authentication to download it for official scores, if you have that authentication you can use the same url that we use in the script.
